### ISSUE TITLE
Topology logic doesn't support new ACT links format

### ISSUE THREAD

**Issue by emilarista** [emilarista/act_topgen#7]
New format, instead of defining neighbors per node and having to define every link in 2 places, this can be used:

```yaml
links:
  - connection:
    - <host1>:<interface>
    - <host2>:<interface>
```
